use crate::models::ProjectSpec;

use super::common;

pub(crate) fn build_main(spec: &ProjectSpec) -> String {
    let env_prefix = common::env_prefix(spec);
    let sqlite_import = if spec.sqlite {
        "from .database import initialize_database\n\n"
    } else {
        ""
    };
    let sqlite_defaults = if spec.sqlite {
        format!(
            ",\n                \"sqlite\": {{\n                    \"enabled\": True,\n                    \"path\": \"data/{package}.db\",\n                }}",
            package = spec.package_name
        )
    } else {
        String::new()
    };
    let sqlite_commands = if spec.sqlite {
        "    db_init = Command(use=\"db-init\", short=\"SQLite 파일과 기본 테이블을 준비한다.\", run=run_db_init)\n    root.add_command(hello, config, db_init)\n"
    } else {
        "    root.add_command(hello, config)\n"
    };
    let sqlite_function = if spec.sqlite {
        format!(
            r#"

def run_db_init(ctx):
    database_path = initialize_database(str(ctx.config.get("sqlite.path", "data/{package}.db")))
    if ctx.logger is not None:
        ctx.logger.info("sqlite initialized", extra={{"path": str(database_path)}})
    print(ctx.terminal.message("success", "SQLite", f"Database ready at {{database_path}}"))
    return 0
"#,
            package = spec.package_name
        )
    } else {
        String::new()
    };
    let grpc_hint = if spec.grpc {
        "    print(ctx.terminal.muted(\"gRPC scaffolding is enabled. Generate stubs with `uv run python tools/generate_grpc.py`.\"))\n"
    } else {
        ""
    };

    format!(
        r#"from __future__ import annotations

import json

from wpycli import Command, ConfigSettings, LoggingSettings

{sqlite_import}APP_NAME = "{project_name}"


def build_root() -> Command:
    root = Command(
        use="{script_name}",
        short="CLI template generated by wpygen",
        long="wpycli, wpyconf, wpylog 조합이 기본 구성된 CLI 템플릿입니다.",
        version="0.1.0",
    )
    root.add_persistent_string_flag("config", help="추가 config.toml 경로", shorthand="c")
    root.add_persistent_string_flag("dotenv", help="추가 .env 경로")
    root.add_persistent_string_flag("log-level", help="로그 레벨 override")
    root.add_persistent_string_flag("log-file", help="로그 파일 경로 override")
    root.configure_runtime(
        config=ConfigSettings(
            defaults={{
                "app": {{
                    "name": APP_NAME,
                    "default_target": "world",
                    "grpc_enabled": {grpc_enabled},
                }},
                "logging": {{"level": "INFO", "file": None}}{sqlite_defaults},
            }},
            files=("config.toml",),
            dotenv=".env",
            env_prefix="{env_prefix}",
            file_flag="config",
            dotenv_flag="dotenv",
        ),
        logging=LoggingSettings(
            logger_name="{package_name}",
            level_flag="log-level",
            log_file_flag="log-file",
        ),
    )

    hello = Command(use="hello [name]", short="인사 메시지를 출력한다.", run=run_hello)
    hello.add_bool_flag("loud", help="대문자로 출력한다.", shorthand="l")
    config = Command(use="config", short="현재 설정을 출력한다.", run=run_config)
{sqlite_commands}    return root


def run_hello(ctx):
    target = ctx.args[0] if ctx.args else str(ctx.config.get("app.default_target", "world"))
    if ctx.flags.get("loud"):
        target = target.upper()

    if ctx.logger is not None:
        ctx.logger.info("hello command invoked", extra={{"target": target}})

    body = f"{{ctx.config.get('app.name', APP_NAME)}} says hello to {{target}}."
    print(ctx.terminal.message("success", "Hello", body))
{grpc_hint}    return 0


def run_config(ctx):
    rendered = json.dumps(ctx.config.as_dict(), indent=2, sort_keys=True)
    print(ctx.terminal.pretty_json(rendered))
    return 0
{sqlite_function}


def main() -> int:
    return build_root().execute()


if __name__ == "__main__":
    raise SystemExit(main())
"#,
        project_name = spec.project_name,
        script_name = spec.project_name.replace('_', "-"),
        grpc_enabled = common::python_bool(spec.grpc),
        sqlite_import = sqlite_import,
        sqlite_defaults = sqlite_defaults,
        env_prefix = env_prefix,
        package_name = spec.package_name,
        sqlite_commands = sqlite_commands,
        grpc_hint = grpc_hint,
        sqlite_function = sqlite_function,
    )
}

pub(crate) fn build_smoke_test(spec: &ProjectSpec) -> String {
    format!(
        r#"from __future__ import annotations

from {package_name}.main import build_root


def test_build_root():
    root = build_root()
    assert root is not None
"#,
        package_name = spec.package_name,
    )
}
